package noppes.npcs.constants;

public enum EnumPlayerPacket {
     FollowerHire,
     FollowerExtend,
     Trader,
     FollowerState,
     Transport,
     BankUnlock,
     BankUpgrade,
     Dialog,
     QuestCompletion,
     CheckQuestCompletion,
     BankSlotOpen,
     FactionsGet,
     MailGet,
     MailDelete,
     MailSend,
     MailRead,
     MailboxOpenMail,
     SignSave,
     SaveBook,
     CompanionOpenInv,
     RoleGet,
     CompanionTalentExp,
     MarkData,
     LeftClick,
     KeyPressed,
     CloseGui;
}
