package noppes.npcs.constants;

public enum EnumPacketClient {
     CHAT,
     MESSAGE,
     DIALOG,
     QUEST_COMPLETION,
     EDIT_NPC,
     PLAY_SOUND,
     PLAY_MUSIC,
     UPDATE_NPC,
     ROLE,
     GUI,
     PARTICLE,
     DELETE_NPC,
     SCROLL_LIST,
     SCROLL_DATA,
     SCROLL_DATA_PART,
     SCROLL_SELECTED,
     GUI_DATA,
     GUI_ERROR,
     GUI_CLOSE,
     VILLAGER_LIST,
     CHATBUBBLE,
     CLONE,
     DIALOG_DUMMY,
     CONFIG,
     EYE_BLINK,
     SYNC_ADD,
     SYNC_END,
     SYNC_UPDATE,
     SYNC_REMOVE,
     MARK_DATA,
     UPDATE_ITEM,
     GUI_UPDATE,
     CHEST_NAME;
}
